Selector:
  task:
    ./my_task
  header:
    - fedavg
  filter: {}
  legend_with: [LR, E, B]

Painter:
  Curve:
    - args:
        x: communication_round
        y: valid_loss
      obj_option:
        linewidth: 5
        color: ['r', 'g', 'b', 'pink', 'orange', 'yellow', 'black', 'gray']
      fig_option:
        xlabel: communication round
        ylabel: valid loss
        title: valid loss on MNIST

  GroupCurve:
    - args:
        x: communication_round
        y: valid_loss
      obj_option:
        linewidth: 5
      fig_option:
        xlabel: communication round
        ylabel: valid loss
        title: valid loss on MNIST

Table:
  min_value:
    - x: valid_loss
      name: min valid loss
  final_value:
    - x: valid_loss
      name: min valid loss
  optimal_x_by_y:
    - x: communication_round
      y: valid_loss
      name: optimal round of valid_loss
  group_optimal_value:
    - x: valid_loss



